### ISSUE TITLE
[PE-D] Inaccurate error command

### ISSUE THREAD

**Issue by nus-se-script** [AY2122s2-CS2113-F12-3/tp#47]
Instead of saying no flight route, program could have identified the input error that was due to the lack of / command and advise accordingly.
![image.png](https://raw.githubusercontent.com/Shyunyin/ped/main/files/822514da-2f4d-4740-8bf5-d9b97f64a1b9.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: Shyunyin/ped#4

**Comment by ElaineQT** [comment]
Redundant words in the command are ignored.
