### ISSUE TITLE
[PE-D] Data integrity issue with Customer and Route data

### ISSUE THREAD

**Issue by nus-se-script** [AY2122s2-CS2113-F12-3/tp#54]
Steps to reproduce:
1. Create a customer
2. Create a route
3. Assign the customer to the route. This will reduce the seats available by 1.
4. Delete the customer.
5. Print routes. The route that the customer was assigned to still has its seat capacity reduced by 1.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: darylhjd/ped#4

**Comment by ElaineQT** [comment]
Fixed #101
