### ISSUE TITLE
[PE-D] Download link in UG is outdated (points to release v1.0)

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122s2-CS2113-F12-3/tp#55]
The download link for the latest version of ARCS is outdated and points to v1.0. Perhaps this should be updated to the current version, or maybe just point it to the releases page which automatically displays the most recent release at the top (so it does not need to be constantly updated with each new release).

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: chooyikai/ped#1

**Comment by johnsuharjono** [comment]
Redirect the link to release page which automatically display the most recent release.
