### ISSUE TITLE
[PE-D] Error not handled

### ISSUE THREAD

**Issue by nus-se-script** [AY2122s2-CS2113-F12-3/tp#67]
Even though stated in the user guide, but error is not handled. There should be an error saying to put an underscore if the next word is not type

![image.png](https://raw.githubusercontent.com/Shyunyin/ped/main/files/c9dfa87c-7007-4991-8f08-f47383fe1d69.png)

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: Shyunyin/ped#9

**Comment by suenalaba** [comment]
Fixed this issue, now if there are no _ separating, the item will not be added at all.
