### ISSUE TITLE
[PE-D] Unwanted system output

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122s2-CS2113-F12-3/tp#69]
Weird not explained lines like here and reach here. 

![image.png](https://raw.githubusercontent.com/Shyunyin/ped/main/files/e99ebac2-ac7c-41ba-9941-1b99f68cff94.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: Shyunyin/ped#10

**Comment by suenalaba** [comment]
Removed debug statements
