### ISSUE TITLE
[PE-D] Quite hard to read list outputs

### ISSUE THREAD

**Issue by nus-se-script** [AY2122s2-CS2113-F12-3/tp#83]
For example, listing long lists of routes or users, it is quite hard to see the demarcation between different routes/users.

Perhaps, should add some padding to show demarcation.

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: darylhjd/ped#10

**Comment by ElaineQT** [comment]
We will consider this in future versions.
