### ISSUE TITLE
[PE-D] Deleting customers with bookings

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122s2-CS2113-F12-3/tp#92]
![image.png](https://raw.githubusercontent.com/thedarie/ped/main/files/1f8765d8-24fa-4388-aa6f-4c743e862cff.png)

Similar to deleting a route with bookings, a customer that has booked a flight can also be deleted.

To reproduce:

`addCustomer ic/W9248013B n/Eddie p/38201843 e/eddie1238@123.com`

`addRoute fid/Bu3037 fd/02172022 ft/11:10 d/singapore s/china c/100`

`book ic/W9248013B fid/Bu3037`

`deleteCustomer 1`

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: thedarie/ped#9

**Comment by ElaineQT** [comment]
We designed the booking records to be all history records, including those bookings whose customers do not exist anymore. Therefore, it is reasonable that a customer who has booked a flight can be removed while the booking records are maintained.
