### ISSUE TITLE
DG Feedback

### ISSUE THREAD

**Issue by kelvneo** [AY2122s2-CS2113-F12-3/tp#95]
- [x] The user stories are not formatted properly in your TP. Add spaces betwen the bars (e.g. `| Version |` instead of `|Version|`) to fix everything.
![image](https://user-images.githubusercontent.com/2332196/161396603-bf5e9f40-40c8-4bcc-b63c-f983c7f210d5.png)
- [x] Add more UML diagrams, such as class diagrams or object diagrams.
- [x] Ensure the formatting of your text is consistent. Use code blocks to reference classes
![image](https://user-images.githubusercontent.com/2332196/161396720-ad3436e3-e47f-47c6-886d-ce7c12fb2c68.png)
- [x] Complete the user testing section, as well as clean up sections you may not need
![image](https://user-images.githubusercontent.com/2332196/161396791-1f06bb3f-cb1f-464b-b563-102c2fc95bbd.png)

**Comment by suenalaba** [comment]
More UML Diagrams added
Fixed User story formatting

**Comment by ElaineQT** [comment]
Added more UML diagrams. Fixed text format. #101

**Comment by suenalaba** [comment]
Verified that all is completed
