### ISSUE TITLE
Code Review for @suenalaba

### ISSUE THREAD

**Issue by kelvneo** [AY2122s2-CS2113-F12-3/tp#97]
@suenalaba  
**Overall**
Good job on the readability of the code! Be sure to write your javadocs.

**In `src/main/java/arcs/commands/menuitem/AddMenuItemCommand.java`**
- [ ] Be sure to remove your debug statements (Line 35)

**In `src/main/java/arcs/parser/Parser.java `**
- [ ] Be sure to remove your debug statements (Line 234)
- [ ] Line 219-227: Try not to use magic strings in your switch statements.

**Comment by suenalaba** [comment]
Fixed magic string literals
